name: cloudwatch_rds_report_bronze
datasource: custom
domain: custos_cloud
ingestion_columns: true
execution_columns: true
description: |-
  ** Propósito: **

  *** Escopo: **

  *** Audiência: **

  *** Processo: **

  *** Recorrência de atualização: **
first_execution: full_load
source:
  path: s3://data-raw-zone-platform-engineering-{env}/observability-platform/finops/cloudwatch-reports/rds/*/*/{year}/{month}/{day}/*.csv
  type: csv
  sep: ','
to:
  database: custos_cloud_bronze
  table: cloudwatch_rds_report
  mode: incremental
