name: labels_kubernetes_report
datasource: custom
domain: custos_cloud
ingestion_columns: true
execution_columns: true
description: |-
  ** Propósito: **

  *** Escopo: **

  *** Audiência: **

  *** Processo: **

  *** Recorrência de atualização: **
first_execution: full_load
source:
  path: s3://data-raw-zone-platform-engineering-prod/observability-platform/finops/labels-kubernetes-report/*.csv
  type: csv
  sep: ','
to:
  database: custos_cloud_bronze
  table: labels_kubernetes_report
  mode: overwrite
