name: atlas_bronze
datasource: custom
domain: custos_cloud
ingestion_columns: true
execution_columns: true
description: |-
  ** Propósito: **

  *** Escopo: **

  *** Audiência: **

  *** Processo: **

  *** Recorrência de atualização: **
first_execution: full_load
source:
  path: s3://data-raw-zone-platform-engineering-prod/observability-platform/finops/atlas-invoice/*/*.csv
  type: csv
  sep: ;
to:
  database: custos_cloud_bronze
  table: mongodb_atlas_cost_usage_report
  mode: overwrite
