name: rds_instances_details
datasource: events
domain: custos_cloud
description: >
      **Propósito:** Este dado é referente as instâncias RDS das contas da AWS.
      **Escopo:** Cada linha representa uma hora.
      **Audiência:** Essa tabela atende ao Time de Observability.
      **Processo:** Os dados são extraídos através do job rds-instances-details através do job no cluster kubernetes finops-kubernetes-jobs.
      **Recorrência de atualização:** A cada uma hora.
source:
  path: s3://data-raw-zone-platform-engineering-{env}/observability-platform/finops/rds-details/*/*/{year}/{month}/{day}/*.csv
  type: CSV
  sep: ","
to:
  table: rds_instances_details
  database: custos_cloud_bronze
  cdc:
    op_column: "Op"
    timestamp_column: "start_date"
    primary_keys: ["id"]
columns:
- name: id
  description: unique_id
  type: string
  nullable: false
  tags: []
- name: start_date
  description: start_date
  type: timestamp
  nullable: false
  tags: []
- name: AWSAccountId
  description: AWSAccountId
  type: string
  nullable: false
  tags: []
- name: Region
  description: Region
  type: string
  nullable: false
  tags: []
- name: DBInstanceIdentifier
  description: DBInstanceIdentifier
  type: string
  nullable: false
  tags: []
- name: DBInstanceClass
  description: DBInstanceClass
  type: string
  nullable: false
  tags: []
- name: Engine
  description: Engine
  type: string
  nullable: false
  tags: []
- name: DBInstanceStatus
  description: DBInstanceStatus
  type: string
  nullable: false
  tags: []
- name: MasterUsername
  description: MasterUsername
  type: string
  nullable: true
  tags: []
- name: DBName
  description: DBName
  type: string
  nullable: true
  tags: []
- name: EndpointAddress
  description: EndpointAddress
  type: string
  nullable: true
  tags: []
- name: AllocatedStorage
  description: AllocatedStorage
  type: integer
  nullable: true
  tags: []
- name: InstanceCreateTime
  description: InstanceCreateTime
  type: timestamp
  nullable: true
  tags: []
- name: PreferredBackupWindow
  description: PreferredBackupWindow
  type: string
  nullable: true
  tags: []
- name: BackupRetentionPeriod
  description: BackupRetentionPeriod
  type: integer
  nullable: true
  tags: []
- name: DBSecurityGroups
  description: DBSecurityGroups
  type: string
  nullable: true
  tags: []
- name: VpcSecurityGroups
  description: VpcSecurityGroups
  type: string
  nullable: true
  tags: []
- name: DBParameterGroups
  description: DBParameterGroups
  type: string
  nullable: true
  tags: []
- name: AvailabilityZone
  description: AvailabilityZone
  type: string
  nullable: true
  tags: []
- name: DBSubnetGroupName
  description: DBSubnetGroupName
  type: string
  nullable: true
  tags: []
- name: PreferredMaintenanceWindow
  description: PreferredMaintenanceWindow
  type: string
  nullable: true
  tags: []
- name: PendingModifiedValues
  description: PendingModifiedValues
  type: string
  nullable: true
  tags: []
- name: MultiAZ
  description: MultiAZ
  type: boolean
  nullable: true
  tags: []
- name: EngineVersion
  description: EngineVersion
  type: string
  nullable: true
  tags: []
- name: AutoMinorVersionUpgrade
  description: AutoMinorVersionUpgrade
  type: boolean
  nullable: true
  tags: []
- name: ReadReplicaDBInstanceIdentifiers
  description: ReadReplicaDBInstanceIdentifiers
  type: string
  nullable: true
  tags: []
- name: LicenseModel
  description: LicenseModel
  type: string
  nullable: true
  tags: []
- name: OptionGroupMemberships
  description: OptionGroupMemberships
  type: string
  nullable: true
  tags: []
- name: PubliclyAccessible
  description: PubliclyAccessible
  type: boolean
  nullable: true
  tags: []
- name: StorageType
  description: StorageType
  type: string
  nullable: true
  tags: []
- name: DbInstancePort
  description: DbInstancePort
  type: integer
  nullable: true
  tags: []
- name: DBClusterIdentifier
  description: DBClusterIdentifier
  type: string
  nullable: true
  tags: []
- name: StorageEncrypted
  description: StorageEncrypted
  type: boolean
  nullable: true
  tags: []
- name: KmsKeyId
  description: KmsKeyId
  type: string
  nullable: true
  tags: []
- name: DbiResourceId
  description: DbiResourceId
  type: string
  nullable: true
  tags: []
- name: CACertificateIdentifier
  description: CACertificateIdentifier
  type: string
  nullable: true
  tags: []
- name: DomainMemberships
  description: DomainMemberships
  type: string
  nullable: true
  tags: []
- name: CopyTagsToSnapshot
  description: CopyTagsToSnapshot
  type: boolean
  nullable: true
  tags: []
- name: MonitoringInterval
  description: MonitoringInterval
  type: integer
  nullable: true
  tags: []
- name: PromotionTier
  description: PromotionTier
  type: integer
  nullable: true
  tags: []
- name: DBInstanceArn
  description: DBInstanceArn
  type: string
  nullable: false
  tags: []
- name: IAMDatabaseAuthenticationEnabled
  description: IAMDatabaseAuthenticationEnabled
  type: boolean
  nullable: true
  tags: []
- name: PerformanceInsightsEnabled
  description: PerformanceInsightsEnabled
  type: boolean
  nullable: true
  tags: []
- name: PerformanceInsightsKMSKeyId
  description: PerformanceInsightsKMSKeyId
  type: string
  nullable: true
  tags: []
- name: PerformanceInsightsRetentionPeriod
  description: PerformanceInsightsRetentionPeriod
  type: integer
  nullable: true
  tags: []
- name: EnabledCloudwatchLogsExports
  description: EnabledCloudwatchLogsExports
  type: string
  nullable: true
  tags: []
- name: DeletionProtection
  description: DeletionProtection
  type: boolean
  nullable: true
  tags: []
- name: AssociatedRoles
  description: AssociatedRoles
  type: string
  nullable: true
  tags: []
- name: TagList
  description: TagList
  type: string
  nullable: true
  tags: []
- name: CustomerOwnedIpEnabled
  description: CustomerOwnedIpEnabled
  type: boolean
  nullable: true
  tags: []
- name: BackupTarget
  description: BackupTarget
  type: string
  nullable: true
  tags: []
- name: Op
  description: Op
  type: string
  nullable: false
  tags: []
